name: Java CI with Maven and Docker in Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    name: Build in Windows
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    # Testcontainers does not yet support Windows containers
    # https://github.com/testcontainers/testcontainers-java/issues/2960
    - name: Build with Maven
      run: mvn verify -Pskip-testcontainers
      working-directory: com.examples.school
