name: Java CI with Maven and Docker in macOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-13

    name: Build in macOS
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Install Docker
      uses: docker/setup-docker-action@v4.1.0
      with:
        set-host: true
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn verify
      working-directory: com.examples.school
      env:
        TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
